version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: calendar_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secure_password_change_me
      MONGO_INITDB_DATABASE: calendar_tasks

  backend:
    build: ./backend
    container_name: calendar_backend
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://admin:secure_password_change_me@mongodb:27017/calendar_tasks?authSource=admin
      - DB_NAME=calendar_tasks
      - CORS_ORIGINS=http://localhost:3000,https://yourdomain.com
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/__pycache__

  frontend:
    build: ./frontend
    container_name: calendar_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=https://yourdomain.com
    depends_on:
      - backend

volumes:
  mongodb_data:

networks:
  default:
    name: calendar_network